sudo: required
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

matrix:
  include:
    - jdk: openjdk8
      before_install:
        - sudo apt-get install openjfx
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
env:
  - EPICS_PVA_ADDR_LIST=127.255.255.255

install: true
script:
  - mvn clean verify -B

after_failure:
 - find ./ -type d -name "surefire-reports" -print0 | xargs -0 -I {} find {} -iname "*.txt" -type f | xargs cat
 - find . -type f -name "*.log" -print0 -exec cat {} \;
